---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: 誕生日おめでとう
description: ウェブページにオンラインのバースデーカードをつくる
original_url: https://projects.raspberrypi.org/ja-JP/projects/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - title: はじめに
  - title: 必要なもの
  - title: HTMLって何？
  - title: 'チャレンジ：段落（だんらく）をもうひとつ追加する'
  - title: CSSって何？
  - title: 'チャレンジ：さらに書式を追加する'
  - title: バースデーカードをつくる
  - title: 'チャレンジ：名前が入ったカードをつくる'
