---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Alles Gute zum Geburtstag
description: Erstelle eine Online-Geburtstagskarte auf einer Webseite
original_url: https://projects.raspberrypi.org/en/projects/happy-birthday
interests: art and design
technologies: html/css
site_areas: codeclub, webdev
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Was ist HTML?
  - 
    title: 'Zusatzaufgabe: Füge einen weiteren Absatz hinzu'
  - 
    title: Was ist CSS?
  - 
    title: 'Zusatzaufgabe: Füge weitere Stile hinzu'
  - 
    title: Eine Geburtstagskarte machen
  - 
    title: 'Zusatzaufgabe: Erstelle eine personalisierte Karte'
