---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Feliz Aniversário
description: Crie um cartão de aniversário on-line em uma página da web
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você vai precisar
  - 
    title: O que é HTML?
  - 
    title: 'Desafio: adicione outro parágrafo'
  - 
    title: O que é CSS?
  - 
    title: 'Desafio: adicione mais estilos'
  - 
    title: Fazendo um cartão de aniversário
  - 
    title: 'Desafio: criar um cartão personalizado'
