hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Feliz Aniversário
description: Neste projeto, você começará a sua jornada pelo HTML e CSS aprendendo a fazer seu próprio cartão de aniversário customizado.
original_url: https://codeclubprojects.org/en-GB/webdev/happy-birthday
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps: 
- title: Feliz Aniversário