---
hero_image: images/happy-birthday.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Per molts anys!
description: Fes una targeta d’aniversari en línia a una pàgina web
original_url: https://projects.raspberrypi.org/ca-ES/codeclub
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: Què és HTML?
  - 
    title: 'Repte: afegeix un altre paràgraf'
  - 
    title: Què és CSS?
  - 
    title: 'Repte: afegeix més estils'
  - 
    title: Fent una targeta d’aniversari
  - 
    title: 'Repte: crea una targeta personalitzada'
